source "https://rubygems.org"
ruby "2.0.0"

gem "sinatra"
gem "sinatra-reloader"
gem "slim"
gem "sass"
gem "coffee-script"
gem "therubyracer", platforms: :ruby
gem "activesupport"
gem "randexp"
gem "omniauth-twitter"
gem "mongoid", git: "https://github.com/mongoid/mongoid.git"
gem "bson_ext"
gem "twitter"
